UBO.projectid.default=mws

UBO.Editor.PartOf.Enabled=true

MCR.EventHandler.MCRObject.019.Class=org.mycore.ubo.publication.PublicationEventHandler
MCR.user2.matching.chain=org.mycore.ubo.matcher.MCRUserMatcherDummy
MCR.user2.IdentityManagement.UserCreation.Unvalidated.Realm=unvalidated
MCR.user2.matching.publication.connection.strategy=uuid
MCR.user2.IdentityManagement.UserCreation.Affiliation=Hagen

UBO.Editable.Attributes=id_gnd,id_orcid,id_local

# show watermark for testinstance on website
UBO.TestInstance=true

# If true, then the nameIdentifier with the lead_id will be removed from the mods element, default is false
# MCR.user2.matching.lead_id.skip=true

MCR.ORCID2.Client.V3.PublicAPI=https://pub.orcid.org/v3.0

######################################################################
#                         Enrichment Resolver                        #
######################################################################

# Configuration to import perspectivia.net data via EnrichmentResolver
# use duepublico2mods - ToDo: add own mir stylesheet
MCR.MODS.EnrichmentResolver.DataSource.perspectivia.IdentifierTypes=mir
MCR.MODS.EnrichmentResolver.DataSource.perspectivia.mir.URI=xslStyle:import/duepublico2mods:https://perspectivia.net/receive/{0}?XSL.Style=xml

# Configuration to import doi via GBV EnrichmentResolver
MCR.MODS.EnrichmentResolver.DataSource.GBV.IdentifierTypes=ppn isbn doi
MCR.MODS.EnrichmentResolver.DataSource.GBV.doi.URI=xslTransform:pica2mods:ratelimit:GBV:https://sru.k10plus.de/%MCR.PICA2MODS.DATABASE%?version=1.1&operation=searchRetrieve&query=pica.doi%3D{1}&maximumRecords=1&recordSchema=picaxml

# Configuration to import new publication by given ID:
MCR.MODS.EnrichmentResolver.DataSources.import=perspectivia (CrossRef PubMed IEEE DataCite arXiv) Unpaywall (LOBID GBV Alma) ZDB JOP

# Configuration to enrich publications imported from BibTeX/ORCID/CSV (import-list.xed):
MCR.MODS.EnrichmentResolver.DataSources.import-list=(CrossRef PubMed IEEE DataCite arXiv) Unpaywall (LOBID GBV Alma) ZDB JOP

